<?php
/**
 * Created by PhpStorm.
 * User: yan
 * Date: 2019/5/18
 * Time: 14:02
 */
namespace App\HttpController\Api;
class Category extends BaseController{
    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub

        return $this->writeJson(200,\Yaconf::get('category.cats'),'OK');
    }
}